use std::env;
use std::fs;
use std::path::Path;

fn main() {
    // tauri_build 仅在桌面构建时调用; server (Docker) 构建无需 Tauri 上下文/资源清单,
    // 跳过它即可在无 webkit2gtk 的 Linux 镜像里编译同一份源码。
    #[cfg(feature = "desktop")]
    tauri_build::build();

    // Windows(MSVC) 桌面 flavor: comctl32 改为**延迟加载**。
    // 根因(2026-07-12 实测): tauri 的 AppHandle drop 胶水使 muda(菜单库)的 About 对话框
    // 对象可达 → 静态导入 TaskDialogIndirect(comctl32 **v6** 专有, 须 manifest 激活上下文
    // 才解析得到)。app bin 有 tauri_build 嵌的 manifest 所以没事; **测试二进制没有 manifest**,
    // 进程加载即 STATUS_ENTRYPOINT_NOT_FOUND, 一个测试都起不来。
    // /DELAYLOAD 后导入在**首次调用**时才解析: 测试从不调对话框 API → 永不解析, 直接可跑;
    // 真实 app 首次调用发生在 UI 线程(manifest 上下文已激活) → 照常解析 v6, 行为零变化。
    let target_windows = env::var("CARGO_CFG_TARGET_OS")
        .map(|s| s == "windows")
        .unwrap_or(false);
    let target_msvc = env::var("CARGO_CFG_TARGET_ENV")
        .map(|s| s == "msvc")
        .unwrap_or(false);
    let desktop = env::var("CARGO_FEATURE_DESKTOP").is_ok();
    if target_windows && target_msvc && desktop {
        println!("cargo::rustc-link-arg=/DELAYLOAD:comctl32.dll");
        // 延迟加载帮手(__delayLoadHelper2)所在的运行时库
        println!("cargo::rustc-link-lib=delayimp");
    }

    // 客户端二进制无法保守共享主密钥：XOR/加壳都可被离线还原。保持兼容常量为空，
    // 停止所有发布构建注入赠送 Key。若恢复赠送额度，必须走带用户鉴权、配额和限流的
    // 服务端代理，客户端只拿短期用户凭据。
    let body = "// AUTO-GENERATED by build.rs — 客户端不嵌入共享 API key。\n\
                pub(crate) const GIFT_MINIMAX_OBF: &[u8] = &[];\n\
                pub(crate) const GIFT_MINIMAX_PAD: &[u8] = &[];\n\
                pub(crate) const GIFT_KIMI_OBF: &[u8] = &[];\n\
                pub(crate) const GIFT_KIMI_PAD: &[u8] = &[];\n";

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    fs::write(Path::new(&out_dir).join("gift_key.rs"), body).expect("write gift_key.rs failed");
}
