use std::env;
use std::fs;
use std::path::Path;

fn main() {
    // 客户端二进制无法保守共享主密钥：XOR/加壳都可被离线还原。保持兼容常量为空，
    // 停止所有发布构建注入赠送 Key。若恢复赠送额度，必须走带用户鉴权、配额和限流的
    // 服务端代理，客户端只拿短期用户凭据。(随 provider/ 从主 crate 迁入。)
    let body = "// AUTO-GENERATED by build.rs — 客户端不嵌入共享 API key。\n\
                pub(crate) const GIFT_MINIMAX_OBF: &[u8] = &[];\n\
                pub(crate) const GIFT_MINIMAX_PAD: &[u8] = &[];\n\
                pub(crate) const GIFT_KIMI_OBF: &[u8] = &[];\n\
                pub(crate) const GIFT_KIMI_PAD: &[u8] = &[];\n";

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    fs::write(Path::new(&out_dir).join("gift_key.rs"), body).expect("write gift_key.rs failed");
}
