//! 百人专家团花名册 — 全量能力卡（编译期内嵌）
//!
//! 来源: VoltAgent/wshobson/awesome-claude-code-subagents (MIT) + 补强自研
//! 2026-07 教师改造: 新增「教师」组 14 人为唯一在役分组，历史分组（含自媒体组）
//! 定义保留、整建制退役（过滤见 expert.rs RETIRED）。

use crate::expert::ExpertCard;

/// 构建单个专家卡片
fn ec(
    id: &'static str,
    name: &'static str,
    icon: &'static str,
    role: &'static str,
    description: &'static str,
    trigger_signals: &[&'static str],
    complements: &'static str,
    keywords: &[&'static str],
    capabilities: &[&'static str],
    claude_md_ref: &'static str,
    model_hint: &'static str,
    cost_tier: u8,
    exclusive_with: &[&'static str],
    source: &'static str,
    license: &'static str,
    group: &'static str,
) -> ExpertCard {
    ExpertCard {
        id: id.to_string(),
        name: name.to_string(),
        icon: icon.to_string(),
        role: role.to_string(),
        description: description.to_string(),
        trigger_signals: trigger_signals.iter().map(|s| s.to_string()).collect(),
        complements: complements.to_string(),
        keywords: keywords.iter().map(|s| s.to_string()).collect(),
        capabilities: capabilities.iter().map(|s| s.to_string()).collect(),
        claude_md_ref: claude_md_ref.to_string(),
        model_hint: model_hint.to_string(),
        cost_tier,
        exclusive_with: exclusive_with.iter().map(|s| s.to_string()).collect(),
        source: source.to_string(),
        license: license.to_string(),
        group: group.to_string(),
    }
}

/// 运行时构建所有专家列表（避免 const 限制）
pub fn build_experts() -> Vec<ExpertCard> {
    vec![
        // ── 编排/统帅 (5) ──
        ec(
            "chief-strategist",
            "首席战略师",
            "🧭",
            "拆解·组队·收口（lead）",
            "任何多步骤、需拆解组队的任务默认入场当编排器",
            &["多步骤", "拆解", "组队", "战略", "规划", "目标"],
            "交付/战略",
            &["planning", "strategy", "orchestration"],
            &["read_code", "run_bash"],
            "experts/orchestration/chief-strategist.md",
            "sonnet",
            3,
            &[],
            "ChatDev/MetaGPT",
            "MIT",
            "orchestration",
        ),
        ec(
            "multi-agent-coordinator",
            "多Agent协调员",
            "🔄",
            "并行调度·依赖管理·交接",
            "子任务≥2 且可独立并行时管调度",
            &["并行", "调度", "多任务", "协作", "Agent"],
            "并行/协调",
            &["parallel", "coordination", "task-scheduling"],
            &["read_code", "run_bash"],
            "experts/orchestration/multi-agent-coordinator.md",
            "sonnet",
            2,
            &[],
            "VoltAgent",
            "MIT",
            "orchestration",
        ),
        ec(
            "knowledge-synthesizer",
            "知识综合器",
            "🧩",
            "跨分支归并·去重·收口",
            "多个并行分支产出需合成一份时",
            &["综合", "归并", "去重", "总结", "汇总"],
            "综合/收口",
            &["synthesis", "merge", "dedup"],
            &["read_code", "run_bash"],
            "experts/orchestration/knowledge-synthesizer.md",
            "sonnet",
            2,
            &[],
            "VoltAgent",
            "MIT",
            "orchestration",
        ),
        ec(
            "strategy-planner",
            "OKR/战略规划",
            "🎯",
            "目标拆里程碑·北极星指标",
            "目标模糊、需先拆成可执行计划时",
            &["OKR", "战略", "规划", "目标", "里程碑", "KPI"],
            "战略/规划",
            &["okr", "strategy", "planning", "metrics"],
            &["read_code", "run_bash"],
            "experts/orchestration/strategy-planner.md",
            "sonnet",
            3,
            &[],
            "补强",
            "北极星综合",
            "orchestration",
        ),
        ec(
            "context-manager",
            "上下文管理器",
            "📋",
            "长上下文·记忆地图维护",
            "长任务多轮、上下文将溢出时",
            &["长上下文", "记忆", "溢出", "上下文", "多轮"],
            "上下文",
            &["context", "memory", "long-context"],
            &["read_code", "run_bash"],
            "experts/orchestration/context-manager.md",
            "sonnet",
            2,
            &[],
            "wshobson",
            "MIT",
            "orchestration",
        ),
        // ── 系统架构 (10) ──
        ec(
            "backend-architect",
            "后端架构师",
            "🏛",
            "API 边界·服务拆分·DB schema",
            "要定接口边界/服务划分/数据建模时",
            &["后端", "API", "服务", "数据库", "架构"],
            "后端/架构",
            &["api", "backend", "database", "architecture"],
            &["read_code", "run_bash"],
            "experts/system/backend-architect.md",
            "sonnet",
            2,
            &[],
            "wshobson",
            "MIT",
            "system_arch",
        ),
        ec(
            "architecture-advisor",
            "系统架构权衡",
            "⚖️",
            "ADR·多方案 trade-off",
            "多方案取舍、需写决策记录时",
            &["架构", "权衡", "trade-off", "ADR", "决策"],
            "架构/决策",
            &["architecture", "tradeoff", "adr"],
            &["read_code", "run_bash"],
            "experts/system/architecture-advisor.md",
            "sonnet",
            3,
            &[],
            "补强",
            "北极星综合",
            "system_arch",
        ),
        ec(
            "api-contract-designer",
            "API契约设计",
            "📡",
            "OpenAPI/gRPC·版本兼容·契约测试",
            "定接口契约、跨端/跨服务对齐时",
            &["API", "契约", "OpenAPI", "gRPC", "接口"],
            "契约/接口",
            &["openapi", "grpc", "api-contract"],
            &["read_code", "run_bash"],
            "experts/system/api-contract-designer.md",
            "sonnet",
            2,
            &[],
            "补强",
            "北极星综合",
            "system_arch",
        ),
        ec(
            "cloud-architect",
            "云架构师",
            "☁️",
            "AWS/Azure/GCP·成本优化",
            "上云选型、跨云、云成本时",
            &["云", "AWS", "Azure", "GCP", "上云"],
            "云/架构",
            &["aws", "azure", "gcp", "cloud"],
            &["read_code", "run_bash"],
            "experts/system/cloud-architect.md",
            "sonnet",
            3,
            &[],
            "wshobson",
            "MIT",
            "system_arch",
        ),
        ec(
            "kubernetes-architect",
            "云原生/K8s架构师",
            "☸️",
            "云原生·GitOps·编排",
            "容器编排/GitOps/集群时",
            &["K8s", "Kubernetes", "Docker", "云原生", "GitOps"],
            "容器/编排",
            &["kubernetes", "docker", "gitops", "cloud-native"],
            &["read_code", "run_bash"],
            "experts/system/kubernetes-architect.md",
            "sonnet",
            2,
            &[],
            "wshobson",
            "MIT",
            "system_arch",
        ),
        ec(
            "microservices-architect",
            "微服务架构师",
            "🔀",
            "拆分·契约·容错",
            "单体拆微服务、服务治理时",
            &["微服务", "拆分", "服务治理", "容错"],
            "微服务",
            &["microservices", "service-mesh", "fault-tolerance"],
            &["read_code", "run_bash"],
            "experts/system/microservices-architect.md",
            "sonnet",
            2,
            &[],
            "VoltAgent",
            "MIT",
            "system_arch",
        ),
        ec(
            "graphql-architect",
            "GraphQL架构师",
            "◈",
            "schema·解析器·联邦",
            "用 GraphQL/联邦图时",
            &["GraphQL", "schema", "联邦"],
            "GraphQL",
            &["graphql", "federation", "schema"],
            &["read_code", "run_bash"],
            "experts/system/graphql-architect.md",
            "sonnet",
            2,
            &[],
            "wshobson",
            "MIT",
            "system_arch",
        ),
        ec(
            "event-sourcing-architect",
            "事件溯源架构师",
            "🔄",
            "CQRS·saga·审计追溯",
            "需事件溯源/审计/最终一致时",
            &["事件溯源", "CQRS", "saga", "审计"],
            "事件溯源",
            &["event-sourcing", "cqrs", "saga", "audit"],
            &["read_code", "run_bash"],
            "experts/system/event-sourcing-architect.md",
            "sonnet",
            3,
            &[],
            "wshobson",
            "MIT",
            "system_arch",
        ),
        ec(
            "platform-engineer-arch",
            "平台工程师",
            "🧱",
            "内部平台·golden path",
            "建内部平台/标准化时",
            &["平台", "内部平台", "DevEx", "golden path"],
            "平台/效率",
            &["platform", "devex", "golden-path"],
            &["read_code", "run_bash"],
            "experts/system/platform-engineer.md",
            "sonnet",
            2,
            &[],
            "VoltAgent",
            "MIT",
            "system_arch",
        ),
        // ── 语言专精 (12) ──
        ec(
            "python-pro",
            "Python专家",
            "🐍",
            "Pythonic·异步·类型",
            "用 Python 实现/异步/性能时",
            &["Python", "python", "异步", "类型"],
            "Python",
            &["python", "async", "typing"],
            &["read_code", "run_bash"],
            "experts/language/python-pro.md",
            "sonnet",
            2,
            &[],
            "wshobson",
            "MIT",
            "language",
        ),
        ec(
            "typescript-pro",
            "TypeScript/Node专家",
            "📘",
            "类型体操·Node 运行时",
            "TS 类型/Node 服务时",
            &["TypeScript", "TS", "Node", "nodejs"],
            "TypeScript",
            &["typescript", "node", "nodejs"],
            &["read_code", "run_bash"],
            "experts/language/typescript-pro.md",
            "sonnet",
            2,
            &[],
            "VoltAgent",
            "MIT",
            "language",
        ),
        ec(
            "golang-pro",
            "Go专家",
            "🔷",
            "并发·高性能·简洁",
            "Go 并发/高吞吐服务时",
            &["Go", "golang", "并发", "高性能"],
            "Go",
            &["golang", "go", "concurrency"],
            &["read_code", "run_bash"],
            "experts/language/golang-pro.md",
            "sonnet",
            2,
            &[],
            "wshobson",
            "MIT",
            "language",
        ),
        ec(
            "rust-pro",
            "Rust专家",
            "🦀",
            "所有权·系统级·零成本",
            "Rust/系统级/native 时",
            &["Rust", "rust", "系统级", "native"],
            "Rust",
            &["rust", "systems", "native"],
            &["read_code", "run_bash"],
            "experts/language/rust-pro.md",
            "sonnet",
            2,
            &[],
            "wshobson",
            "MIT",
            "language",
        ),
        ec(
            "java-pro",
            "Java专家",
            "☕",
            "JVM·Spring 生态",
            "JVM/Spring 后端时",
            &["Java", "JVM", "Spring"],
            "Java",
            &["java", "jvm", "spring"],
            &["read_code", "run_bash"],
            "experts/language/java-pro.md",
            "sonnet",
            2,
            &[],
            "VoltAgent",
            "MIT",
            "language",
        ),
        ec(
            "cpp-pro",
            "C/C++专家",
            "⚙️",
            "系统级·内存·模板",
            "native/内存敏感/高性能时",
            &["C++", "cpp", "内存", "系统级"],
            "C++",
            &["cpp", "c++", "memory", "systems"],
            &["read_code", "run_bash"],
            "experts/language/cpp-pro.md",
            "sonnet",
            3,
            &[],
            "wshobson",
            "MIT",
            "language",
        ),
        ec(
            "csharp-pro",
            "C#专家",
            "🔷",
            ".NET·Unity·LINQ",
            ".NET/Unity 时",
            &["C#", "csharp", ".NET", "Unity"],
            "C#",
            &["csharp", "dotnet", "unity"],
            &["read_code", "run_bash"],
            "experts/language/csharp-pro.md",
            "sonnet",
            2,
            &[],
            "VoltAgent",
            "MIT",
            "language",
        ),
        ec(
            "sql-pro",
            "SQL专家",
            "🗄️",
            "复杂查询·窗口函数·调优",
            "写复杂 SQL/查询调优时",
            &["SQL", "查询", "数据库", "调优"],
            "SQL",
            &["sql", "query", "database", "tuning"],
            &["read_code", "run_bash"],
            "experts/language/sql-pro.md",
            "sonnet",
            2,
            &[],
            "wshobson",
            "MIT",
            "language",
        ),
        ec(
            "ios-developer",
            "Swift/iOS专家",
            "🍎",
            "SwiftUI·原生体验",
            "iOS 原生 App 时",
            &["iOS", "Swift", "SwiftUI", "Apple"],
            "iOS",
            &["ios", "swift", "swiftui", "apple"],
            &["read_code", "run_bash"],
            "experts/language/ios-developer.md",
            "sonnet",
            2,
            &[],
            "wshobson",
            "MIT",
            "language",
        ),
        ec(
            "kotlin-specialist",
            "Kotlin/Android专家",
            "🤖",
            "协程·Jetpack",
            "Android 原生时",
            &["Kotlin", "Android", "Jetpack"],
            "Kotlin",
            &["kotlin", "android", "jetpack"],
            &["read_code", "run_bash"],
            "experts/language/kotlin-specialist.md",
            "sonnet",
            2,
            &[],
            "VoltAgent",
            "MIT",
            "language",
        ),
        ec(
            "blockchain-developer",
            "Solidity/区块链",
            "⛓️",
            "智能合约·Web3·链上审计",
            "智能合约/Web3/链上时",
            &["Solidity", "区块链", "Web3", "智能合约"],
            "Web3",
            &["solidity", "blockchain", "web3", "smart-contract"],
            &["read_code", "run_bash"],
            "experts/language/blockchain-developer.md",
            "sonnet",
            3,
            &[],
            "VoltAgent",
            "MIT",
            "language",
        ),
        ec(
            "embedded-systems",
            "嵌入式/IoT",
            "📟",
            "固件·实时·低功耗",
            "固件/实时/硬件交互时",
            &["嵌入式", "IoT", "固件", "ARM", "RTOS"],
            "嵌入式",
            &["embedded", "iot", "firmware", "rtos"],
            &["read_code", "run_bash"],
            "experts/language/embedded-systems.md",
            "sonnet",
            3,
            &[],
            "VoltAgent",
            "MIT",
            "language",
        ),
        // ── 前端/移动 (4) ──
        // Web 前端统一为一位「前端专家」(React/Vue/Next 通吃)，视觉交给 11 位设计师库；
        // 不再拆成 React/Vue/Next/前端架构 多个同质专家，避免一个前端任务被路由成一队。
        ec(
            "frontend-engineer",
            "前端专家",
            "🎨",
            "React/Vue/Next 通吃·组件·状态·性能·视觉调设计师库",
            "任何 Web 前端/界面/组件/状态/性能/SSR 任务",
            &[
                "前端",
                "界面",
                "组件",
                "状态",
                "性能",
                "架构",
                "React",
                "hooks",
                "Vue",
                "组合式API",
                "Next.js",
                "SSR",
                "RSC",
                "全栈",
            ],
            "Web 前端工程与界面",
            &[
                "frontend",
                "react",
                "hooks",
                "vue",
                "nextjs",
                "ssr",
                "rsc",
                "fullstack",
                "component",
                "state",
                "ui",
            ],
            &["read_code", "run_bash"],
            "experts/frontend/frontend-engineer.md",
            "sonnet",
            2,
            &[],
            "北极星综合",
            "MIT",
            "frontend",
        ),
        ec(
            "flutter-expert",
            "Flutter专家",
            "🦋",
            "跨端·动画",
            "跨端 App/动画时",
            &["Flutter", "跨端", "Dart"],
            "Flutter",
            &["flutter", "cross-platform", "dart"],
            &["read_code", "run_bash"],
            "experts/frontend/flutter-expert.md",
            "sonnet",
            2,
            &[],
            "VoltAgent",
            "MIT",
            "frontend",
        ),
        ec(
            "accessibility-tester",
            "无障碍审计员",
            "♿",
            "WCAG·a11y",
            "无障碍合规/可访问性时",
            &["无障碍", "WCAG", "a11y", "可访问性"],
            "无障碍",
            &["wcag", "accessibility", "a11y"],
            &["read_code", "run_bash"],
            "experts/frontend/accessibility-tester.md",
            "sonnet",
            1,
            &[],
            "VoltAgent",
            "MIT",
            "frontend",
        ),
        ec(
            "mobile-developer",
            "移动端专家",
            "📱",
            "跨平台移动·原生体验",
            "iOS/Android 跨平台时",
            &["移动", "iOS", "Android", "跨平台"],
            "移动端",
            &["mobile", "ios", "android", "cross-platform"],
            &["read_code", "run_bash"],
            "experts/frontend/mobile-developer.md",
            "sonnet",
            2,
            &[],
            "VoltAgent",
            "MIT",
            "frontend",
        ),
        // ── DevOps/基础设施 (9) ──
        ec(
            "devops-engineer",
            "DevOps工程师",
            "🔧",
            "流水线·自动化",
            "建 CI 流水线/自动化时",
            &["DevOps", "CI", "流水线", "自动化"],
            "DevOps",
            &["devops", "ci", "pipeline", "automation"],
            &["read_code", "run_bash"],
            "experts/devops/devops-engineer.md",
            "sonnet",
            2,
            &[],
            "VoltAgent",
            "MIT",
            "devops",
        ),
        ec(
            "deployment-engineer",
            "CICD部署工程师",
            "🚀",
            "容器化·发布编排",
            "上线/发布/灰度时",
            &["部署", "CICD", "发布", "灰度"],
            "部署",
            &["deploy", "cicd", "release", "canary"],
            &["read_code", "run_bash"],
            "experts/devops/deployment-engineer.md",
            "sonnet",
            2,
            &[],
            "wshobson",
            "MIT",
            "devops",
        ),
        ec(
            "terraform-specialist",
            "Terraform/IaC专家",
            "🏗️",
            "基础设施即代码·状态",
            "用 IaC 管基础设施时",
            &["Terraform", "IaC", "基础设施"],
            "IaC",
            &["terraform", "iac", "infrastructure"],
            &["read_code", "run_bash"],
            "experts/devops/terraform-specialist.md",
            "sonnet",
            2,
            &[],
            "wshobson",
            "MIT",
            "devops",
        ),
        ec(
            "docker-expert",
            "Docker专家",
            "🐳",
            "镜像瘦身·多阶段",
            "容器化/镜像优化时",
            &["Docker", "容器", "镜像"],
            "Docker",
            &["docker", "container", "image"],
            &["read_code", "run_bash"],
            "experts/devops/docker-expert.md",
            "sonnet",
            1,
            &[],
            "VoltAgent",
            "MIT",
            "devops",
        ),
        ec(
            "sre-engineer",
            "SRE/可观测性",
            "📊",
            "SLO·告警·事故复盘",
            "可靠性/监控/postmortem 时",
            &["SRE", "可观测性", "SLO", "告警"],
            "SRE",
            &["sre", "observability", "slo", "alerting"],
            &["read_code", "run_bash"],
            "experts/devops/sre-engineer.md",
            "sonnet",
            2,
            &[],
            "VoltAgent",
            "MIT",
            "devops",
        ),
        ec(
            "network-engineer",
            "网络工程师",
            "🌐",
            "负载均衡·流量·排障",
            "网络/流量/连通性排障时",
            &["网络", "负载均衡", "DNS", "流量"],
            "网络",
            &["network", "load-balancing", "dns"],
            &["read_code", "run_bash"],
            "experts/devops/network-engineer.md",
            "sonnet",
            2,
            &[],
            "wshobson",
            "MIT",
            "devops",
        ),
        ec(
            "incident-responder",
            "事故响应官",
            "🚨",
            "生产故障·紧急止血",
            "线上故障/P0 紧急时",
            &["故障", "P0", "事故", "紧急"],
            "事故",
            &["incident", "p0", "emergency"],
            &["read_code", "run_bash"],
            "experts/devops/incident-responder.md",
            "sonnet",
            3,
            &[],
            "wshobson",
            "MIT",
            "devops",
        ),
        ec(
            "ops-engineer",
            "运维工程师",
            "⚙️",
            "运维·监控·巡检",
            "日常运维/监控/巡检时",
            &["运维", "监控", "巡检"],
            "运维",
            &["ops", "monitoring"],
            &["read_code", "run_bash"],
            "experts/devops/ops-engineer.md",
            "sonnet",
            2,
            &[],
            "VoltAgent",
            "MIT",
            "devops",
        ),
        ec(
            "platform-engineer-devops",
            "平台工程师",
            "🧱",
            "内部平台·golden path",
            "建内部平台/标准化时",
            &["平台", "内部平台", "DevEx"],
            "平台",
            &["platform", "devex"],
            &["read_code", "run_bash"],
            "experts/devops/platform-engineer.md",
            "sonnet",
            2,
            &[],
            "VoltAgent",
            "MIT",
            "devops",
        ),
        // ── 数据 (8) ──
        ec(
            "data-scientist",
            "数据科学家",
            "🔬",
            "建模·统计·洞察",
            "建模/统计/数据洞察时",
            &["数据科学", "建模", "统计", "ML"],
            "数据科学",
            &["data-science", "modeling", "statistics", "ml"],
            &["read_code", "run_bash"],
            "experts/data/data-scientist.md",
            "sonnet",
            3,
            &[],
            "wshobson",
            "MIT",
            "data",
        ),
        ec(
            "data-engineer",
            "数据工程师",
            "🔄",
            "ETL·数仓·流式",
            "建数据管道/数仓时",
            &["数据工程", "ETL", "数仓", "流式"],
            "数据工程",
            &["data-engineering", "etl", "data-warehouse"],
            &["read_code", "run_bash"],
            "experts/data/data-engineer.md",
            "sonnet",
            2,
            &[],
            "wshobson",
            "MIT",
            "data",
        ),
        ec(
            "data-analyst",
            "数据分析师",
            "📈",
            "指标·可视化·归因",
            "指标分析/归因/报表时",
            &["数据分析", "指标", "可视化", "归因"],
            "分析",
            &["data-analysis", "metrics", "visualization"],
            &["read_code", "run_bash"],
            "experts/data/data-analyst.md",
            "sonnet",
            1,
            &[],
            "VoltAgent",
            "MIT",
            "data",
        ),
        ec(
            "database-architect",
            "数据库架构师",
            "🗄️",
            "选型·schema 建模",
            "选库/建表/数据建模时",
            &["数据库", "选型", "schema"],
            "数据库",
            &["database", "schema", "modeling"],
            &["read_code", "run_bash"],
            "experts/data/database-architect.md",
            "sonnet",
            2,
            &[],
            "wshobson",
            "MIT",
            "data",
        ),
        ec(
            "database-optimizer",
            "数据库优化师",
            "⚡",
            "慢查询·索引·迁移",
            "慢查询/索引/迁移时",
            &["数据库优化", "慢查询", "索引"],
            "优化",
            &["database", "optimization", "query-tuning"],
            &["read_code", "run_bash"],
            "experts/data/database-optimizer.md",
            "sonnet",
            2,
            &[],
            "wshobson",
            "MIT",
            "data",
        ),
        ec(
            "vector-db-engineer",
            "向量数据库工程师",
            "🔮",
            "embedding 存储·ANN",
            "RAG/向量检索/ANN 时",
            &["向量数据库", "embedding", "RAG", "ANN"],
            "向量检索",
            &["vector-db", "embedding", "rag", "ann"],
            &["read_code", "run_bash"],
            "experts/data/vector-db-engineer.md",
            "sonnet",
            2,
            &[],
            "wshobson",
            "MIT",
            "data",
        ),
        ec(
            "data-contract-engineer",
            "数据契约/质量",
            "📋",
            "schema 演进·血缘·校验",
            "数据质量/契约/血缘时",
            &["数据契约", "数据质量", "血缘", "schema"],
            "数据质量",
            &["data-contract", "data-quality", "lineage"],
            &["read_code", "run_bash"],
            "experts/data/data-contract-engineer.md",
            "sonnet",
            2,
            &[],
            "补强",
            "北极星综合",
            "data",
        ),
        ec(
            "dataviz-storyteller",
            "数据可视化叙事",
            "📊",
            "图表选型·数据故事",
            "把数据讲成图表故事/数据→PPT 时",
            &["数据可视化", "图表", "叙事"],
            "可视化",
            &["dataviz", "chart", "storytelling"],
            &["read_code", "run_bash"],
            "experts/data/dataviz-storyteller.md",
            "sonnet",
            2,
            &[],
            "补强",
            "北极星综合",
            "data",
        ),
        // ── AI/机器学习 (7) ──
        ec(
            "ai-engineer",
            "AI工程师",
            "🤖",
            "prompt 流水线·RAG·agent",
            "做 LLM/RAG/agent 应用时",
            &["AI", "LLM", "RAG", "agent", "prompt"],
            "AI/LLM",
            &["ai", "llm", "rag", "agent", "prompt"],
            &["read_code", "run_bash"],
            "experts/ai/ai-engineer.md",
            "sonnet",
            3,
            &[],
            "wshobson",
            "MIT",
            "ai_ml",
        ),
        ec(
            "ml-engineer",
            "ML工程师",
            "🧠",
            "训练·部署·调优",
            "训练/部署模型时",
            &["ML", "机器学习", "训练", "部署"],
            "ML",
            &["ml", "machine-learning", "training"],
            &["read_code", "run_bash"],
            "experts/ai/ml-engineer.md",
            "sonnet",
            3,
            &[],
            "wshobson",
            "MIT",
            "ai_ml",
        ),
        ec(
            "mlops-engineer",
            "MLOps工程师",
            "🔄",
            "模型流水线·监控",
            "模型上线/监控/版本时",
            &["MLOps", "模型", "监控", "流水线"],
            "MLOps",
            &["mlops", "model-monitoring"],
            &["read_code", "run_bash"],
            "experts/ai/mlops-engineer.md",
            "sonnet",
            2,
            &[],
            "VoltAgent",
            "MIT",
            "ai_ml",
        ),
        ec(
            "llm-architect",
            "LLM架构师",
            "🧠",
            "推理服务·上下文工程·成本",
            "LLM 推理服务/上下文/成本时",
            &["LLM架构", "推理", "上下文工程", "成本"],
            "LLM架构",
            &["llm", "inference", "context-engineering"],
            &["read_code", "run_bash"],
            "experts/ai/llm-architect.md",
            "sonnet",
            3,
            &[],
            "VoltAgent",
            "MIT",
            "ai_ml",
        ),
        ec(
            "nlp-engineer",
            "NLP工程师",
            "📝",
            "文本抽取·分类",
            "文本处理/抽取/分类时",
            &["NLP", "文本", "抽取", "分类"],
            "NLP",
            &["nlp", "text-processing", "classification"],
            &["read_code", "run_bash"],
            "experts/ai/nlp-engineer.md",
            "sonnet",
            2,
            &[],
            "VoltAgent",
            "MIT",
            "ai_ml",
        ),
        ec(
            "prompt-engineer",
            "提示词工程师",
            "💬",
            "prompt 设计·评测",
            "设计/优化/评测 prompt 时",
            &["prompt", "提示词", "评测"],
            "提示词",
            &["prompt", "prompt-engineering"],
            &["read_code", "run_bash"],
            "experts/ai/prompt-engineer.md",
            "sonnet",
            2,
            &[],
            "wshobson",
            "MIT",
            "ai_ml",
        ),
        ec(
            "rl-engineer",
            "强化学习工程师",
            "🎮",
            "RL·策略优化",
            "强化学习/策略优化时",
            &["强化学习", "RL", "策略"],
            "RL",
            &["reinforcement-learning", "rl", "policy"],
            &["read_code", "run_bash"],
            "experts/ai/rl-engineer.md",
            "sonnet",
            3,
            &[],
            "VoltAgent",
            "MIT",
            "ai_ml",
        ),
        // ── 安全/合规 (7) ──
        ec(
            "security-auditor",
            "安全审计员",
            "🔍",
            "OWASP·漏洞·供应链",
            "涉鉴权/对外接口/漏洞/合规时",
            &["安全", "审计", "OWASP", "漏洞", "渗透"],
            "安全",
            &["security", "audit", "owasp", "vulnerability"],
            &["read_code", "run_bash"],
            "experts/security/security-auditor.md",
            "sonnet",
            3,
            &[],
            "wshobson",
            "MIT",
            "security",
        ),
        ec(
            "penetration-tester",
            "渗透测试员",
            "🗡️",
            "攻击面·利用链",
            "验证攻击面/红队时",
            &["渗透", "红队", "攻击面"],
            "渗透测试",
            &["penetration", "red-team", "attack-surface"],
            &["read_code", "run_bash"],
            "experts/security/penetration-tester.md",
            "sonnet",
            3,
            &[],
            "VoltAgent",
            "MIT",
            "security",
        ),
        ec(
            "threat-modeling-expert",
            "威胁建模专家",
            "⚠️",
            "STRIDE·体系化风险",
            "系统性风险评估/设计评审时",
            &["威胁建模", "STRIDE", "风险"],
            "威胁建模",
            &["threat-modeling", "stride", "risk"],
            &["read_code", "run_bash"],
            "experts/security/threat-modeling-expert.md",
            "sonnet",
            3,
            &[],
            "wshobson",
            "MIT",
            "security",
        ),
        ec(
            "appsec-coder",
            "应用安全工程师",
            "🛡️",
            "XSS/CSP·注入防御",
            "处理用户输入/防注入编码时",
            &["应用安全", "XSS", "注入", "CSP"],
            "应用安全",
            &["appsec", "xss", "injection", "csp"],
            &["read_code", "run_bash"],
            "experts/security/appsec-coder.md",
            "sonnet",
            2,
            &[],
            "wshobson",
            "MIT",
            "security",
        ),
        ec(
            "compliance-privacy",
            "合规/隐私",
            "📜",
            "GDPR·数据出境·AI 合规",
            "处理个人数据/跨境/AI 合规时",
            &["合规", "GDPR", "隐私", "AI合规"],
            "合规",
            &["compliance", "gdpr", "privacy", "ai-compliance"],
            &["read_code", "run_bash"],
            "experts/security/compliance-privacy.md",
            "sonnet",
            2,
            &[],
            "VoltAgent",
            "MIT",
            "security",
        ),
        ec(
            "license-counsel",
            "法务/许可证",
            "⚖️",
            "开源 license·合同条款",
            "引第三方/开源 license 审查时",
            &["license", "许可证", "开源", "法务"],
            "法务",
            &["license", "open-source", "legal"],
            &["read_code", "run_bash"],
            "experts/security/license-counsel.md",
            "sonnet",
            2,
            &[],
            "wshobson",
            "MIT",
            "security",
        ),
        ec(
            "privacy-engineer",
            "密码学/数据隐私",
            "🔐",
            "加密·脱敏·密钥",
            "加密/脱敏/密钥管理时",
            &["加密", "脱敏", "密钥", "隐私"],
            "隐私",
            &["encryption", "anonymization", "key-management"],
            &["read_code", "run_bash"],
            "experts/security/privacy-engineer.md",
            "sonnet",
            3,
            &[],
            "VoltAgent",
            "MIT",
            "security",
        ),
        // ── 质量/治理 (7) ──
        ec(
            "code-reviewer",
            "代码评审员",
            "👀",
            "可读性·缺陷·模式",
            "合并前/质量把关时",
            &["代码评审", "review", "代码质量"],
            "评审",
            &["code-review", "review", "quality"],
            &["read_code", "run_bash"],
            "experts/quality/code-reviewer.md",
            "sonnet",
            2,
            &[],
            "wshobson",
            "MIT",
            "quality",
        ),
        ec(
            "test-automator",
            "测试自动化工程师",
            "🧪",
            "E2E·覆盖率·回归",
            "建自动化测试/回归时",
            &["测试", "自动化", "E2E", "回归"],
            "测试",
            &["testing", "e2e", "automation", "regression"],
            &["read_code", "run_bash"],
            "experts/quality/test-automator.md",
            "sonnet",
            2,
            &[],
            "wshobson",
            "MIT",
            "quality",
        ),
        ec(
            "qa-expert",
            "QA专家",
            "✅",
            "测试策略·用例",
            "定测试策略/设计用例时",
            &["QA", "测试策略", "用例"],
            "QA",
            &["qa", "test-strategy", "test-case"],
            &["read_code", "run_bash"],
            "experts/quality/qa-expert.md",
            "sonnet",
            1,
            &[],
            "VoltAgent",
            "MIT",
            "quality",
        ),
        ec(
            "performance-engineer",
            "性能工程师",
            "⚡",
            "剖析·瓶颈·调优",
            "性能瓶颈/卡顿/调优时",
            &["性能", "瓶颈", "优化", "profiling"],
            "性能",
            &["performance", "profiling", "bottleneck"],
            &["read_code", "run_bash"],
            "experts/quality/performance-engineer.md",
            "sonnet",
            3,
            &[],
            "wshobson",
            "MIT",
            "quality",
        ),
        ec(
            "debugger",
            "调试专家",
            "🔧",
            "复现·定位·根因",
            "难复现 bug/根因定位时",
            &["调试", "bug", "复现", "根因"],
            "调试",
            &["debug", "bug", "reproduce"],
            &["read_code", "run_bash"],
            "experts/quality/debugger.md",
            "sonnet",
            2,
            &[],
            "wshobson",
            "MIT",
            "quality",
        ),
        ec(
            "refactoring-specialist",
            "重构专家",
            "♻️",
            "坏味道·解耦",
            "代码腐化/解耦/可维护时",
            &["重构", "坏味道", "解耦"],
            "重构",
            &["refactoring", "clean-code", "decoupling"],
            &["read_code", "run_bash"],
            "experts/quality/refactoring-specialist.md",
            "sonnet",
            2,
            &[],
            "VoltAgent",
            "MIT",
            "quality",
        ),
        ec(
            "tech-debt-strategist",
            "技术债治理",
            "💳",
            "识别·量化·排期偿还",
            "技术债盘点/排期偿还时",
            &["技术债", "治理", "偿还"],
            "技术债",
            &["tech-debt", "refactoring"],
            &["read_code", "run_bash"],
            "experts/quality/tech-debt-strategist.md",
            "sonnet",
            2,
            &[],
            "补强",
            "北极星综合",
            "quality",
        ),
        // ── 专项技术 (6) ──
        ec(
            "payment-integration",
            "支付集成专家",
            "💳",
            "网关·对账·订阅",
            "带支付/计费/对账/退款时",
            &["支付", "Stripe", "计费", "对账", "退款", "订阅"],
            "支付",
            &["payment", "stripe", "billing", "subscription"],
            &["read_code", "run_bash"],
            "experts/specialty/payment-integration.md",
            "sonnet",
            2,
            &[],
            "VoltAgent",
            "MIT",
            "specialty",
        ),
        ec(
            "game-developer",
            "游戏开发者",
            "🎮",
            "引擎·循环·物理",
            "做游戏/引擎/物理时",
            &["游戏", "引擎", "Unity", "Unreal"],
            "游戏",
            &["game", "unity", "game-engine"],
            &["read_code", "run_bash"],
            "experts/specialty/game-developer.md",
            "sonnet",
            2,
            &[],
            "VoltAgent",
            "MIT",
            "specialty",
        ),
        ec(
            "legacy-modernizer",
            "遗留系统现代化",
            "🏚️",
            "渐进迁移·绞杀者",
            "老系统迁移/重写时",
            &["遗留系统", "迁移", "现代化"],
            "遗留",
            &["legacy", "migration", "modernization"],
            &["read_code", "run_bash"],
            "experts/specialty/legacy-modernizer.md",
            "sonnet",
            3,
            &[],
            "wshobson",
            "MIT",
            "specialty",
        ),
        ec(
            "browser-automation",
            "浏览器自动化",
            "🌐",
            "爬取·反检测·RPA",
            "爬取/RPA/网页操控时",
            &["浏览器自动化", "爬虫", "RPA", "CloakBrowser"],
            "浏览器",
            &["browser", "automation", "crawl", "rpa"],
            &["read_code", "run_bash"],
            "experts/specialty/browser-automation.md",
            "sonnet",
            2,
            &[],
            "VoltAgent",
            "MIT",
            "specialty",
        ),
        ec(
            "fintech-engineer",
            "资金/支付系统专家",
            "💹",
            "支付·交易·对账·风控·合规",
            "支付/计费/对账/退款/订阅 或 金融/交易/风控系统时（已合并支付集成专家）",
            &[
                "支付",
                "计费",
                "对账",
                "退款",
                "订阅",
                "金融科技",
                "交易",
                "风控",
                "合规",
                "Stripe",
            ],
            "资金/支付",
            &[
                "payment",
                "stripe",
                "billing",
                "subscription",
                "fintech",
                "trading",
                "risk-management",
            ],
            &["read_code", "run_bash"],
            "experts/specialty/fintech-engineer.md",
            "sonnet",
            3,
            &[],
            "VoltAgent",
            "MIT",
            "specialty",
        ),
        ec(
            "technical-writer-pro",
            "技术写作者",
            "✍️",
            "README·白皮书·对外文档",
            "写对外文档/README/白皮书时",
            &["技术写作", "README", "文档"],
            "写作",
            &["technical-writing", "readme", "documentation"],
            &["read_code", "run_bash"],
            "experts/specialty/technical-writer-pro.md",
            "sonnet",
            1,
            &[],
            "VoltAgent",
            "MIT",
            "specialty",
        ),
        // ── 文档/技术写作 (5) ──
        ec(
            "docs-architect",
            "文档架构师",
            "📚",
            "Diátaxis·信息架构",
            "建文档体系/信息架构时",
            &["文档", "Diátaxis", "信息架构"],
            "文档",
            &["documentation", "diataxis"],
            &["read_code", "run_bash"],
            "experts/docs/docs-architect.md",
            "sonnet",
            2,
            &[],
            "wshobson",
            "MIT",
            "docs",
        ),
        ec(
            "api-documenter",
            "API文档师",
            "📡",
            "OpenAPI·示例·参考",
            "写 API 文档/参考手册时",
            &["API文档", "OpenAPI", "参考"],
            "API文档",
            &["api-docs", "openapi", "reference"],
            &["read_code", "run_bash"],
            "experts/docs/api-documenter.md",
            "sonnet",
            1,
            &[],
            "wshobson",
            "MIT",
            "docs",
        ),
        ec(
            "tutorial-engineer",
            "教程工程师",
            "📖",
            "循序渐进·可跑",
            "写上手教程/可跑示例时",
            &["教程", "示例", "上手"],
            "教程",
            &["tutorial", "example", "onboarding"],
            &["read_code", "run_bash"],
            "experts/docs/tutorial-engineer.md",
            "sonnet",
            2,
            &[],
            "wshobson",
            "MIT",
            "docs",
        ),
        ec(
            "mermaid-expert",
            "图表专家",
            "📊",
            "流程图·时序·架构图",
            "要画流程/时序/架构图时",
            &["图表", "Mermaid", "流程图", "时序"],
            "图表",
            &["mermaid", "diagram", "flowchart"],
            &["read_code", "run_bash"],
            "experts/docs/mermaid-expert.md",
            "sonnet",
            1,
            &[],
            "wshobson",
            "MIT",
            "docs",
        ),
        ec(
            "technical-writer",
            "技术写作",
            "✍️",
            "README·白皮书·对外文档",
            "写对外文档/README/白皮书时",
            &["技术写作", "README", "白皮书"],
            "写作",
            &["technical-writing", "readme"],
            &["read_code", "run_bash"],
            "experts/docs/technical-writer.md",
            "sonnet",
            1,
            &[],
            "VoltAgent",
            "MIT",
            "docs",
        ),
        // ── 产品/项目/战略 (8) ──
        ec(
            "product-manager",
            "产品经理",
            "📦",
            "PRD·优先级·取舍",
            "写 PRD/排优先级/需求取舍时",
            &["产品经理", "PRD", "优先级", "需求"],
            "产品",
            &["product", "prd", "prioritization"],
            &["read_code", "run_bash"],
            "experts/product/product-manager.md",
            "sonnet",
            2,
            &[],
            "MetaGPT",
            "MIT",
            "product",
        ),
        ec(
            "delivery-manager",
            "项目交付管理",
            "📅",
            "风险登记·依赖·关键路径",
            "管交付/风险/依赖/排期时",
            &["交付", "项目管理", "风险", "依赖"],
            "交付",
            &["delivery", "project-management", "risk"],
            &["read_code", "run_bash"],
            "experts/product/delivery-manager.md",
            "sonnet",
            1,
            &[],
            "VoltAgent",
            "MIT",
            "product",
        ),
        ec(
            "scrum-master",
            "Scrum Master",
            "🏃",
            "迭代·阻塞清除",
            "跑迭代/清障/敏捷时",
            &["Scrum", "敏捷", "迭代"],
            "Scrum",
            &["scrum", "agile", "iteration"],
            &["read_code", "run_bash"],
            "experts/product/scrum-master.md",
            "sonnet",
            1,
            &[],
            "VoltAgent",
            "MIT",
            "product",
        ),
        ec(
            "business-analyst",
            "业务分析师",
            "📊",
            "需求·流程·指标",
            "需求/流程/业务建模时",
            &["业务分析", "需求", "流程"],
            "业务",
            &["business-analysis", "requirements"],
            &["read_code", "run_bash"],
            "experts/product/business-analyst.md",
            "sonnet",
            2,
            &[],
            "wshobson",
            "MIT",
            "product",
        ),
        ec(
            "ux-researcher",
            "用户研究",
            "👥",
            "访谈·JTBD·可用性",
            "用户访谈/可用性/需求挖掘时",
            &["用户研究", "访谈", "JTBD"],
            "用户研究",
            &["ux", "user-research", "jtdb"],
            &["read_code", "run_bash"],
            "experts/product/ux-researcher.md",
            "sonnet",
            2,
            &[],
            "VoltAgent",
            "MIT",
            "product",
        ),
        ec(
            "growth-experimenter",
            "增长实验设计",
            "📈",
            "A/B·北极星指标·漏斗",
            "做增长/A-B 测试/漏斗时",
            &["增长", "A/B测试", "漏斗"],
            "增长",
            &["growth", "ab-test", "funnel"],
            &["read_code", "run_bash"],
            "experts/product/growth-experimenter.md",
            "sonnet",
            2,
            &[],
            "补强",
            "北极星综合",
            "product",
        ),
        ec(
            "financial-modeler",
            "财务建模",
            "💰",
            "单位经济·定价·ROI",
            "算账/单位经济/ROI 测算时",
            &["财务建模", "ROI", "单位经济", "定价"],
            "财务",
            &["financial", "roi", "unit-economics"],
            &["read_code", "run_bash"],
            "experts/product/financial-modeler.md",
            "sonnet",
            3,
            &[],
            "补强",
            "北极星综合",
            "product",
        ),
        ec(
            "pricing-strategist",
            "定价策略",
            "💵",
            "定价模型·弹性·打包",
            "定价/打包/商业化时",
            &["定价", "定价策略", "商业化"],
            "定价",
            &["pricing", "monetization"],
            &["read_code", "run_bash"],
            "experts/product/pricing-strategist.md",
            "sonnet",
            2,
            &[],
            "NicholasSpisak",
            "未明示",
            "product",
        ),
        // ── 研究/分析 (7) ──
        ec(
            "deep-research",
            "深度研究",
            "🔬",
            "多源检索·对抗校验",
            "调研/综述/尽调/选型时",
            &["深度研究", "调研", "尽调", "选型"],
            "研究",
            &["research", "due-diligence"],
            &["read_code", "run_bash"],
            "experts/research/deep-research.md",
            "sonnet",
            3,
            &[],
            "wshobson",
            "MIT",
            "research",
        ),
        ec(
            "competitive-analyst",
            "竞品分析",
            "🔍",
            "对标·差异·定位",
            "对标竞品/找差异定位时",
            &["竞品分析", "对标", "竞争"],
            "竞品",
            &["competitive-analysis", "competitor"],
            &["read_code", "run_bash"],
            "experts/research/competitive-analyst.md",
            "sonnet",
            2,
            &[],
            "VoltAgent",
            "MIT",
            "research",
        ),
        ec(
            "market-researcher",
            "市场研究",
            "🌍",
            "规模·趋势·机会",
            "算市场规模/找机会时",
            &["市场研究", "市场规模", "趋势"],
            "市场",
            &["market-research", "market-size"],
            &["read_code", "run_bash"],
            "experts/research/market-researcher.md",
            "sonnet",
            2,
            &[],
            "VoltAgent",
            "MIT",
            "research",
        ),
        ec(
            "trend-analyst",
            "趋势分析",
            "📊",
            "信号·拐点·预测",
            "判趋势/信号/拐点时",
            &["趋势", "拐点", "预测"],
            "趋势",
            &["trend", "analysis"],
            &["read_code", "run_bash"],
            "experts/research/trend-analyst.md",
            "sonnet",
            2,
            &[],
            "contains-studio",
            "未明示",
            "research",
        ),
        ec(
            "scientific-researcher",
            "科学文献研究",
            "📚",
            "论文综述·证据分级",
            "论文综述/技术前沿/证据时",
            &["科学文献", "论文", "综述"],
            "文献",
            &["scientific", "literature", "paper"],
            &["read_code", "run_bash"],
            "experts/research/scientific-researcher.md",
            "sonnet",
            3,
            &[],
            "VoltAgent",
            "MIT",
            "research",
        ),
        ec(
            "osint-analyst",
            "OSINT情报分析",
            "🔎",
            "公开情报·溯源·尽调",
            "公开情报/背调/溯源时",
            &["OSINT", "情报", "背调"],
            "情报",
            &["osint", "intelligence"],
            &["read_code", "run_bash"],
            "experts/research/osint-analyst.md",
            "sonnet",
            2,
            &[],
            "补强",
            "北极星综合",
            "research",
        ),
        ec(
            "research-analyst",
            "研究分析师",
            "📋",
            "综合研究·分析报告",
            "综合研究/分析报告时",
            &["研究分析", "报告"],
            "研究",
            &["research", "analysis"],
            &["read_code", "run_bash"],
            "experts/research/research-analyst.md",
            "sonnet",
            2,
            &[],
            "补强",
            "北极星综合",
            "research",
        ),
        // ── 营销/内容 (8) ──
        ec(
            "content-marketer",
            "内容营销策略",
            "📣",
            "内容矩阵·转化漏斗",
            "规划内容矩阵/转化时",
            &["内容营销", "矩阵", "转化"],
            "营销",
            &["content-marketing", "content-strategy"],
            &["read_code", "run_bash"],
            "experts/marketing/content-marketer.md",
            "sonnet",
            1,
            &[],
            "wshobson",
            "MIT",
            "marketing",
        ),
        ec(
            "seo-specialist",
            "SEO专家",
            "🔍",
            "关键词·结构·收录",
            "SEO/搜索收录/排名时",
            &["SEO", "搜索", "收录"],
            "SEO",
            &["seo", "search", "ranking"],
            &["read_code", "run_bash"],
            "experts/marketing/seo-specialist.md",
            "sonnet",
            1,
            &[],
            "wshobson",
            "MIT",
            "marketing",
        ),
        ec(
            "growth-hacker",
            "增长黑客",
            "🚀",
            "裂变·获客·留存",
            "裂变/获客/留存增长时",
            &["增长黑客", "获客", "留存"],
            "增长",
            &["growth-hacking", "acquisition"],
            &["read_code", "run_bash"],
            "experts/marketing/growth-hacker.md",
            "sonnet",
            2,
            &[],
            "contains-studio",
            "未明示",
            "marketing",
        ),
        ec(
            "social-media-manager",
            "社媒运营",
            "📱",
            "公众号/小红书/X 运营",
            "自媒体发布/运营时",
            &["社媒", "小红书", "公众号", "运营"],
            "社媒",
            &["social-media", "operations"],
            &["read_code", "run_bash"],
            "experts/marketing/social-media-manager.md",
            "sonnet",
            1,
            &[],
            "contains-studio",
            "未明示",
            "marketing",
        ),
        ec(
            "brand-storyteller",
            "叙事官/品牌故事",
            "🎭",
            "钩子·情绪曲线",
            "成品要打动人/讲故事时",
            &["品牌故事", "叙事", "钩子"],
            "品牌",
            &["brand", "storytelling"],
            &["read_code", "run_bash"],
            "experts/marketing/brand-storyteller.md",
            "sonnet",
            3,
            &[],
            "contains-studio",
            "未明示",
            "marketing",
        ),
        ec(
            "visual-designer",
            "视觉设计",
            "🎨",
            "版式·视觉叙事·PPT 美学",
            "要好看/版式/视觉时",
            &["视觉设计", "PPT", "版式"],
            "视觉",
            &["visual-design", "layout"],
            &["read_code", "run_bash"],
            "experts/marketing/visual-designer.md",
            "sonnet",
            2,
            &[],
            "contains-studio",
            "未明示",
            "marketing",
        ),
        ec(
            "pitch-coach",
            "路演/演讲教练",
            "🎤",
            "结构·表达·台风",
            "PPT/路演/对外汇报表达时",
            &["路演", "演讲", "表达"],
            "演讲",
            &["pitch", "presentation", "speaking"],
            &["read_code", "run_bash"],
            "experts/marketing/pitch-coach.md",
            "sonnet",
            1,
            &[],
            "f/awesome-chatgpt-prompts",
            "MIT+CC0",
            "marketing",
        ),
        ec(
            "copywriter",
            "文案/口播",
            "✍️",
            "标题·口播稿·钩子",
            "写文案/口播稿/标题/幽默钩子时",
            &["文案", "口播", "标题", "钩子"],
            "文案",
            &["copywriting", "headline", "hook"],
            &["read_code", "run_bash"],
            "experts/marketing/copywriter.md",
            "sonnet",
            1,
            &[],
            "f/awesome-chatgpt-prompts",
            "MIT+CC0",
            "marketing",
        ),
        // ── 自媒体统一专家团 (14) ──────────────────────────────────
        // 唯一在役分组：其余历史分组的专家全部退役（见 expert.rs RETIRED），
        // 平台文风不写死在画像里，由「平台补丁」运行时叠加（overlays/{platform}--{id}.md）。
        ec(
            "media-strategist",
            "选题战略官",
            "🎯",
            "自媒体选题·爆款切角·内容规划（lead）",
            "自媒体运营的编排者：把一个粗想法拆成「选哪个平台、切什么角度、给谁看、排什么期」的可执行选题，领衔整支自媒体团。",
            &[
                "选题", "爆款", "热点", "切入角度", "切角", "内容规划", "自媒体",
                "涨粉", "选平台", "内容日历",
            ],
            "选题战略与编排",
            &[
                "topic", "strategy", "hot-topic", "angle", "content-calendar", "editorial",
            ],
            &["read_code", "run_bash"],
            "experts/media/media-strategist.md",
            "sonnet",
            1,
            &[],
            "北极星自媒体",
            "MIT",
            "media",
        ),
        ec(
            "media-researcher",
            "情报员",
            "🔦",
            "背景调研·素材信源·事实底稿",
            "为选题准备弹药：搜集背景资料、权威信源、数据素材，产出可追溯的调研底稿，供主笔与事实核查官取用。",
            &[
                "情报", "调研", "资料", "素材", "背景", "信源", "找资料", "查资料",
            ],
            "调研与素材",
            &["research", "material", "source", "evidence"],
            &["read_code", "run_bash"],
            "experts/media/media-researcher.md",
            "sonnet",
            1,
            &[],
            "北极星自媒体",
            "MIT",
            "media",
        ),
        ec(
            "media-writer",
            "主笔",
            "✍️",
            "正文写作·平台文风·钩子结构",
            "把选题与素材写成能读下去的正文；平台文风（公众号/小红书/知乎…）不由本画像决定，而由运行时的平台补丁注入；始终规避 AI 腔。",
            &[
                "写作", "主笔", "正文", "初稿", "写文章", "文章", "笔记", "写稿",
                "公众号", "小红书", "知乎", "口播", "文风",
            ],
            "正文写作",
            &["writing", "draft", "article", "copy", "narrative"],
            &["read_code", "run_bash"],
            "experts/media/media-writer.md",
            "sonnet",
            2,
            &[],
            "北极星自媒体",
            "MIT",
            "media",
        ),
        ec(
            "media-typesetter",
            "排版师",
            "🎨",
            "平台排版·富文本·视觉节奏",
            "把正文排成各平台原生观感的富文本/图文：字阶、留白、分隔、引导线；排版规范由平台补丁给定。",
            &[
                "排版", "版式", "样式", "富文本", "段落", "公众号排版", "美化", "版面",
            ],
            "排版与版式",
            &["typesetting", "layout", "format", "richtext"],
            &["read_code", "run_bash"],
            "experts/media/media-typesetter.md",
            "sonnet",
            1,
            &[],
            "北极星自媒体",
            "MIT",
            "media",
        ),
        ec(
            "media-publisher",
            "投递员",
            "📮",
            "多平台草稿投递（铁律：只存草稿绝不发布）",
            "把排好的图文投进各平台创作后台，只保存为草稿，绝不点发布；适配 7 平台的登录态与草稿箱，失败降级为手动辅助。",
            &[
                "投递", "发布", "草稿", "上传", "发文", "多平台", "投稿", "存草稿",
            ],
            "草稿投递",
            &["publish", "draft", "upload", "distribute"],
            &["read_code", "run_bash"],
            "experts/media/media-publisher.md",
            "sonnet",
            1,
            &[],
            "北极星自媒体",
            "MIT",
            "media",
        ),
        ec(
            "media-reviewer",
            "七维评审官",
            "🧭",
            "七维质检·打分·退回",
            "对成稿做七维评审（选题价值/结构/信息密度/可读性/平台契合/合规/标题），逐维打分并给出可执行修改单，是交付前的质量闸门 A。",
            &[
                "评审", "质检", "七维", "打分", "审稿", "质量", "把关", "验收",
            ],
            "质量评审",
            &["review", "score", "quality", "rubric"],
            &["read_code", "run_bash"],
            "experts/media/media-reviewer.md",
            "sonnet",
            2,
            &[],
            "北极星自媒体",
            "MIT",
            "media",
        ),
        ec(
            "media-critic",
            "杠精",
            "😈",
            "对抗性挑刺·唱反调·压力测试",
            "专职唱反调：用最刻薄的读者视角挑逻辑漏洞、夸张失实、自嗨表达。刻意换供应商模型以避免与主笔同源同味，形成真正的对抗。",
            &[
                "杠精", "抬杠", "挑刺", "反驳", "质疑", "批判", "唱反调", "找茬",
            ],
            "对抗性批判",
            &["critic", "devil-advocate", "red-team", "adversarial"],
            &["read_code", "run_bash"],
            "experts/media/media-critic.md",
            // 故意换供应商模型：与主笔（Anthropic 系）不同源，避免同质自我肯定。
            "deepseek-v3（换供应商·对抗去同源同味）",
            2,
            &[],
            "北极星自媒体",
            "MIT",
            "media",
        ),
        ec(
            "media-factchecker",
            "事实核查官",
            "🔍",
            "闸门B·数字查证·无法核实即降级",
            "交付前的第二道闸门：核对每一个数字、时间、人名、引语与出处；凡无法核实的量化表述一律降级为模糊表述或删除，绝不放行硬编的“事实”。",
            &[
                "事实核查", "核查", "查证", "数据核实", "真实性", "出处", "求证", "核对",
            ],
            "事实核查",
            &["factcheck", "verify", "citation", "accuracy"],
            &["read_code", "run_bash"],
            "experts/media/media-factchecker.md",
            "sonnet",
            1,
            &[],
            "北极星自媒体",
            "MIT",
            "media",
        ),
        ec(
            "media-deaiflavor",
            "AI痕迹优化师",
            "🫧",
            "去AI腔·口语化·人味重塑",
            "专治“AI 味”：清除套话、排比癖、总分总模板腔、破折号泛滥，注入真实语气、具体细节与个人视角，让文字像人写的。",
            &[
                "AI痕迹", "AI味", "去味", "口语化", "人味", "降AI", "去AI腔", "机器味",
            ],
            "去AI腔",
            &["de-ai", "humanize", "tone", "naturalize"],
            &["read_code", "run_bash"],
            "experts/media/media-deaiflavor.md",
            "sonnet",
            1,
            &[],
            "北极星自媒体",
            "MIT",
            "media",
        ),
        ec(
            "media-imagedirector",
            "图卡导演",
            "🖼️",
            "配图脚本·封面·图卡视觉",
            "为文章设计配图方案与封面：给出每张图的画面脚本、构图与文字叠加建议，对接文生图（Ark/豆包）生成，把控视觉一致性。",
            &[
                "配图", "图卡", "封面", "插图", "视觉", "生成图", "文生图", "图片",
            ],
            "配图与封面",
            &["image", "cover", "illustration", "visual"],
            &["read_code", "run_bash"],
            "experts/media/media-imagedirector.md",
            "sonnet",
            1,
            &[],
            "北极星自媒体",
            "MIT",
            "media",
        ),
        ec(
            "media-analytics",
            "度量分析师",
            "📈",
            "数据复盘·指标归因·迭代建议",
            "把阅读量、完读、转化、涨粉等度量事件汇成 KPI，做同比与归因，给出下一轮选题与文风的迭代建议。",
            &[
                "度量", "数据分析", "阅读量", "转化", "复盘", "指标", "归因", "KPI",
            ],
            "度量分析",
            &["analytics", "metrics", "kpi", "attribution"],
            &["read_code", "run_bash"],
            "experts/media/media-analytics.md",
            "sonnet",
            1,
            &[],
            "北极星自媒体",
            "MIT",
            "media",
        ),
        ec(
            "media-accountkeeper",
            "账号管家",
            "🔑",
            "登录态·养号·矩阵健康",
            "维护 7 平台账号的登录态与 profile 目录、监测限流与封控风险、给出养号与发布节奏建议，保障投递链路可用。",
            &[
                "账号", "登录", "养号", "账号管家", "矩阵", "限流", "封号", "掉登录",
            ],
            "账号运维",
            &["account", "login", "profile", "matrix"],
            &["read_code", "run_bash"],
            "experts/media/media-accountkeeper.md",
            "sonnet",
            1,
            &[],
            "北极星自媒体",
            "MIT",
            "media",
        ),
        ec(
            "media-competitor",
            "竞品哨兵",
            "🛰️",
            "对标账号·爆文拆解·选题反哺",
            "盯同赛道标杆账号：拆解爆款的选题、钩子、结构与发布节奏，反哺自家选题库，只做借鉴不做搬运。",
            &[
                "竞品", "对标", "爆文拆解", "同行", "哨兵", "对标账号", "拆解爆款",
            ],
            "竞品情报",
            &["competitor", "benchmark", "teardown", "trend"],
            &["read_code", "run_bash"],
            "experts/media/media-competitor.md",
            "sonnet",
            1,
            &[],
            "北极星自媒体",
            "MIT",
            "media",
        ),
        ec(
            "media-georestructurer",
            "旧文改造师",
            "♻️",
            "旧文翻新·一稿多改·跨平台适配",
            "把已有旧文/长文按目标平台重构：换角度、改结构、调文风、拆条数，实现一源多发而非机械洗稿，保留原创内核。",
            &[
                "旧文改造", "改写", "一稿多发", "翻新", "旧文", "重构文章", "一稿多改",
                "跨平台适配",
            ],
            "旧文改造",
            &["repurpose", "rewrite", "adapt", "geo"],
            &["read_code", "run_bash"],
            "experts/media/media-georestructurer.md",
            "sonnet",
            1,
            &[],
            "北极星自媒体",
            "MIT",
            "media",
        ),
        // ── 教师专家团 (14) ──────────────────────────────────────
        // 唯一在役分组：2026-07 教师改造，自媒体组整建制退役（定义保留，见 expert.rs RETIRED）。
        // 学段差异（小学/初中/高中）不写死在画像里，由「学段补丁」运行时叠加
        // （overlays/{xiaoxue|chuzhong|gaozhong}--{id}.md）。
        ec(
            "teacher-headcoach",
            "教学总设计师",
            "🧭",
            "拆解教学任务·组阵·收口（lead）",
            "教师团的编排者：把老师的一句话需求拆成「备什么课、出什么题、给谁用、何时交」的可执行任务链，决定召集哪些专家并统一收口，领衔整支教师团。",
            &[
                "教学设计", "教学规划", "学期计划", "教学安排", "单元设计", "课程规划",
                "教学目标", "整体方案", "教学任务",
            ],
            "教学编排与收口",
            &[
                "teaching-design", "curriculum", "unit-plan", "orchestration", "planning",
            ],
            &["read_code", "run_bash"],
            "experts/teacher/teacher-headcoach.md",
            "sonnet",
            1,
            &[],
            "北极星教师",
            "MIT",
            "teacher",
        ),
        ec(
            "teacher-lessonplanner",
            "备课设计师",
            "📖",
            "教案·学案·目标-评价-活动一致性",
            "把教学目标写成能直接上课的教案与学案：课时切分、重难点突破、教学环节与时间轴；学段差异（小学/初中/高中）由运行时的学段补丁注入，始终守教学评一致性。",
            &[
                "备课", "教案", "学案", "课时", "教学环节", "重难点", "导入", "说课",
                "公开课", "磨课稿",
            ],
            "备课与教学设计",
            &["lesson-plan", "teaching", "objectives", "instruction"],
            &["read_code", "run_bash"],
            "experts/teacher/teacher-lessonplanner.md",
            "sonnet",
            2,
            &[],
            "北极星教师",
            "MIT",
            "teacher",
        ),
        ec(
            "teacher-courseware",
            "课件工匠",
            "🖥️",
            "教学PPT·板书设计·演示素材",
            "把教案变成认知友好的课件与板书：一页一个认知点、图示优先、动画只为引导注意，不做花哨堆砌；配套板书布局与演示节奏建议。",
            &[
                "课件", "PPT", "ppt", "幻灯片", "板书", "演示文稿", "教学课件", "插图",
            ],
            "课件与板书",
            &["courseware", "slides", "blackboard", "visual"],
            &["read_code", "run_bash"],
            "experts/teacher/teacher-courseware.md",
            "sonnet",
            1,
            &[],
            "北极星教师",
            "MIT",
            "teacher",
        ),
        ec(
            "teacher-itemwriter",
            "命题专家",
            "✒️",
            "出题·组卷·双向细目表·难度控制",
            "按双向细目表原创命题与组卷：知识点覆盖、难度梯度、区分度与作答时长测算；题型规范按学段补丁执行，绝不照抄真题。",
            &[
                "出题", "命题", "组卷", "试卷", "试题", "题目", "双向细目表", "测验",
                "周测", "月考", "期中", "期末", "难度",
            ],
            "命题与组卷",
            &["assessment", "exam", "item-writing", "quiz", "test"],
            &["read_code", "run_bash"],
            "experts/teacher/teacher-itemwriter.md",
            "sonnet",
            2,
            &[],
            "北极星教师",
            "MIT",
            "teacher",
        ),
        ec(
            "teacher-grader",
            "作业批改官",
            "✅",
            "批改标准·评语·错因归类",
            "制定可执行的批改标准并批量出评语：评语具体、指向改进、保护自尊；同步归类错因，喂给学情分析师与培优补差师。",
            &[
                "批改", "作业", "评语", "打分", "判卷", "阅卷", "错因", "点评", "作业设计",
            ],
            "批改与评语",
            &["grading", "feedback", "homework", "rubric"],
            &["read_code", "run_bash"],
            "experts/teacher/teacher-grader.md",
            "sonnet",
            1,
            &[],
            "北极星教师",
            "MIT",
            "teacher",
        ),
        ec(
            "teacher-learninganalyst",
            "学情分析师",
            "📊",
            "成绩分析·学情画像·分层归因",
            "把成绩单与作业数据变成学情结论：分数段分布、优秀率及格率、进退步归因、分层名单建议；只下数据支持得住的结论，不贴标签。",
            &[
                "学情", "成绩分析", "成绩", "分数段", "均分", "优秀率", "及格率",
                "学情画像", "进步", "退步", "薄弱点",
            ],
            "学情与数据",
            &["analytics", "score-analysis", "learning-profile", "data"],
            &["read_code", "run_bash"],
            "experts/teacher/teacher-learninganalyst.md",
            "sonnet",
            1,
            &[],
            "北极星教师",
            "MIT",
            "teacher",
        ),
        ec(
            "teacher-tutor",
            "培优补差师",
            "🎯",
            "分层辅导·错题变式·个性化提升",
            "按学情分层设计辅导路径：补差先补断点、培优给拔高台阶；围绕错题做变式训练与再检测，路径可执行、量在双减红线内。",
            &[
                "培优", "补差", "辅导", "分层", "错题", "变式", "提分", "个性化",
                "薄弱生", "尖子生",
            ],
            "分层辅导",
            &["tutoring", "differentiation", "remedial", "variation"],
            &["read_code", "run_bash"],
            "experts/teacher/teacher-tutor.md",
            "sonnet",
            1,
            &[],
            "北极星教师",
            "MIT",
            "teacher",
        ),
        ec(
            "teacher-classmaster",
            "班主任军师",
            "🛡️",
            "班级管理·班会·德育·突发处置",
            "给班主任出可落地的招：班规与座位策略、主题班会设计、德育活动、突发事件处置预案；涉心理危机一律建议转介专业人员，不越界。",
            &[
                "班主任", "班级管理", "班会", "德育", "纪律", "座位", "班规",
                "学生冲突", "早恋", "手机管理",
            ],
            "班级管理",
            &["class-management", "homeroom", "moral-education", "discipline"],
            &["read_code", "run_bash"],
            "experts/teacher/teacher-classmaster.md",
            "sonnet",
            1,
            &[],
            "北极星教师",
            "MIT",
            "teacher",
        ),
        ec(
            "teacher-parentliaison",
            "家校沟通师",
            "🤝",
            "家长沟通话术·通知·家长会",
            "把难开口的话写得体面有效：家长沟通话术、群通知公告、家长会方案与发言稿；立场永远是家校同盟，措辞不引战、不甩锅、不告状式。",
            &[
                "家长", "家校", "家长会", "通知", "话术", "家访", "群公告", "沟通",
            ],
            "家校沟通",
            &["parent", "communication", "notice", "meeting"],
            &["read_code", "run_bash"],
            "experts/teacher/teacher-parentliaison.md",
            "sonnet",
            1,
            &[],
            "北极星教师",
            "MIT",
            "teacher",
        ),
        ec(
            "teacher-activitydesigner",
            "活动设计师",
            "🎨",
            "课堂活动·小组合作·PBL·跨学科",
            "设计服务于教学目标的活动：课堂互动、小组合作机制、项目式学习（PBL）与跨学科主题；每个活动都有目标锚点与评价方式，不为热闹而热闹。",
            &[
                "课堂活动", "互动", "游戏化", "项目式", "PBL", "pbl", "跨学科",
                "小组合作", "情境", "实践活动", "研学",
            ],
            "活动与项目式学习",
            &["activity", "pbl", "interdisciplinary", "cooperative"],
            &["read_code", "run_bash"],
            "experts/teacher/teacher-activitydesigner.md",
            "sonnet",
            1,
            &[],
            "北极星教师",
            "MIT",
            "teacher",
        ),
        ec(
            "teacher-researchwriter",
            "教研写作导师",
            "📝",
            "论文·课题·教学反思·案例分析",
            "指导教研写作全流程：选题聚焦、框架搭建、教学论文与课题申报书、教学反思与案例分析；用真实课例与真实数据，绝不编造参考文献。",
            &[
                "论文", "课题", "教研", "教学反思", "开题", "结题", "案例分析",
                "文献", "教学研究",
            ],
            "教研写作",
            &["research", "paper", "reflection", "case-study"],
            &["read_code", "run_bash"],
            "experts/teacher/teacher-researchwriter.md",
            "sonnet",
            2,
            &[],
            "北极星教师",
            "MIT",
            "teacher",
        ),
        ec(
            "teacher-docwriter",
            "行政文书官",
            "📋",
            "计划总结·述职·申报表格",
            "包办教师的行政文书：工作计划与总结、述职报告、评职称与评优申报材料、各类表格填报；格式规范、要点齐全、一次成稿。",
            &[
                "工作计划", "总结", "述职", "评职称", "申报", "汇报材料", "表格",
                "文书", "评优",
            ],
            "行政文书",
            &["document", "report", "application", "admin"],
            &["read_code", "run_bash"],
            "experts/teacher/teacher-docwriter.md",
            "sonnet",
            1,
            &[],
            "北极星教师",
            "MIT",
            "teacher",
        ),
        ec(
            "teacher-factchecker",
            "学科把关人",
            "🔍",
            "闸门A·知识准确性·科学性核查",
            "交付前的知识闸门：核查概念错误、科学性错误、过时表述与超纲误用；凡无法核实的知识性表述一律要求降级或删除，绝不放行错误知识进课堂。",
            &[
                "知识点核查", "科学性", "概念错误", "核对", "查证", "准确性",
                "知识性错误", "超纲",
            ],
            "知识核查",
            &["factcheck", "accuracy", "subject-matter", "verify"],
            &["read_code", "run_bash"],
            "experts/teacher/teacher-factchecker.md",
            "sonnet",
            1,
            &[],
            "北极星教师",
            "MIT",
            "teacher",
        ),
        ec(
            "teacher-reviewer",
            "教学评审官",
            "⚖️",
            "闸门B·四维评审·打回重做",
            "交付前的质量闸门：按课标对齐、教学评一致、可操作性、学段适切四维逐项打分，给出可执行修改单；任一维不合格即打回对应专家重做。",
            &[
                "评审", "质检", "审核", "验收", "评课", "打回", "课标", "质量",
            ],
            "教学评审",
            &["review", "rubric", "standard-alignment", "quality"],
            &["read_code", "run_bash"],
            "experts/teacher/teacher-reviewer.md",
            "sonnet",
            2,
            &[],
            "北极星教师",
            "MIT",
            "teacher",
        ),
    ]
}
